sudo: required

services:
    - docker

language: cpp

before_install:
    - docker pull ubuntu:latest

compiler: gcc
script:
    - docker run -v${PWD}:/source -t ubuntu:yakkety bash -c "apt-get update && apt-get install -y g++ cmake libboost-all-dev && cd /source && mkdir build && cd build && cmake .. && make run-all"

